apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.yaml
- request-authentication.yaml
- authorization-policy.yaml
- envoy-filter.yaml
- peerauthentication.yaml
- destination-rules.yaml
- service-authorization.yaml
