apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Bases are the same, through patches we add the things needed for prod
resources:
- ../../base/infrastructure/mongodb
- ../../base/infrastructure/postgresql
- ../../base/infrastructure/redis
- ../../base/infrastructure/kafka
- ../../base/infrastructure/rabbitmq
- ../../base/istio-config
- ../../base/frontend
- ../../base/services/content-service
- ../../base/services/user-identity-service
- ../../base/services/product-catalogue-service
- ../../base/services/order-service
- ../../base/services/shoppingcart-wishlist-service
- ../../base/services/support-service
- ../../base/services/notifications-service
- ../../base/services/reporting-and-analysis-service
- istio
images:
- name: cso2/ai-service
  newName: ghcr.io/cso2/ai_service
  newTag: main-c7fa651
- name: cso2/content-service
  newName: ghcr.io/cso2/content_service
  newTag: main-60f0d72
- name: cso2/frontend
  newName: ghcr.io/cso2/frontend_web
  newTag: main-11f67da
- name: cso2/notifications-service
  newName: ghcr.io/cso2/notifications_service
  newTag: main-dd7903f
- name: cso2/order-service
  newName: ghcr.io/cso2/order_service
  newTag: main-b8004ae
- name: cso2/product-catalogue-service
  newName: ghcr.io/cso2/product_catalogue_service
  newTag: main-ae47511
- name: cso2/reporting-and-analysis-service
  newName: ghcr.io/cso2/reporting_and_analysis_service
  newTag: main-0265e27
- name: cso2/shoppingcart-wishlist-service
  newName: ghcr.io/cso2/shoppingcart_wishlist_service
  newTag: main-8438112
- name: cso2/support-service
  newName: ghcr.io/cso2/support_service
  newTag: main-5a2374c
- name: cso2/user-identity-service
  newName: ghcr.io/cso2/user_identity_service
  newTag: main-d540e52
