apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Bases are the same, through patches we add the things needed for prod
resources:
- ../../base/infrastructure/mongodb
- ../../base/infrastructure/postgresql
- ../../base/infrastructure/redis
- ../../base/infrastructure/kafka
- ../../base/infrastructure/rabbitmq
- ../../base/istio-config
- ../../base/frontend
- ../../base/services/content-service
- ../../base/services/user-identity-service
- ../../base/services/product-catalogue-service
- ../../base/services/order-service
- ../../base/services/shoppingcart-wishlist-service
- ../../base/services/support-service
- ../../base/services/notifications-service
- ../../base/services/reporting-and-analysis-service
- istio
images:
- name: cso2/content-service
  newName: ghcr.io/cso2/content_service
  newTag: main-570f7b8
- name: cso2/frontend
  newName: ghcr.io/cso2/frontend_web
  newTag: main-11f67da
- name: cso2/reporting-and-analysis-service
  newName: ghcr.io/cso2/reporting_and_analysis_service
  newTag: main-a2facbe
- name: cso2/support-service
  newName: ghcr.io/cso2/support_service
  newTag: main-6f9c281
