apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-service
  template:
    metadata:
      labels:
        app: support-service
        type: backend-service
    spec:
      containers:
      - name: spring-boot
        image: cso2/support-service:latest
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: support-service-config
        - secretRef:
            name: support-service-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
