plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: cso2-ecommerce
keyed_groups:
  - key: tags.Role
    prefix: role
  - key: tags.Name
    prefix: name
compose:
  ansible_host: public_ip_address
