apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalogue-service
  template:
    metadata:
      labels:
        app: product-catalogue-service
    spec:
      containers:
      - name: spring-boot
        image: cso2/product-catalogue-service:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: product-catalogue-service-config
        - secretRef:
            name: product-catalogue-service-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
